services:
  php-fpm:
    container_name: php
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      - PHP_IDE_CONFIG=serverName=test_task
    networks:
      - empty.project.network

  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - empty.project.network

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    networks:
        - empty.project.network
    environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
        - ./docker/postgres/datadir:/var/lib/postgresql/data
    ports:
        - "8432:5432"

networks:
  empty.project.network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.132.0/28
